SerFy v2.0/Models/Comment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SerFy_v2._0.Models
{
    public class Comment
    {
        //comment ID
        [key]
        public int ID { get; set; }
        //Comment itself
        public string Text { get; set; }
        //Movie
        [ForeignKey("Movie")]
        public int MovieFK { get; set; }
        public virtual Movie Movie { get; set; }
        //User
        [ForeignKey("User")]
        public int UserFK { get; set; }
        public virtual User User { get; set; }
    }
}

SerFy v2.0/Models/Rate.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SerFy_v2._0.Models
{
    public class Rate
    {
        //Rate ID
        public int ID { get; set; }
        //rate value
        public int rate { get; set; }
        
        //Movie being Rate 
        [ForeignKey("Movie")]
        public int MovieFK { get; set; }
        public Movie Movie { get; set; }

        //user that rates
        [ForeignKey("User")]
        public int UserFK { get; set; }
        public virtual User User { get; set; }
    }
}

SerFy v2.0/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SerFy_v2._0.Models;

namespace SerFy_v2._0.Controllers
{
    public class CommentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Comments
        public ActionResult Index()
        {
            return View(db.Comments.ToList());
        }

        // GET: Comments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // GET: Comments/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Comments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Text,MovieFK")] Comment comment)
        {
            //gets the user
            var utilizador = db.Utilizadores.Where(u => u.email == User.Identity.Name).FirstOrDefault();
            //adds the userFK
            comment.UserFK = utilizador.ID;


            if (ModelState.IsValid)
            {
                //adds the comment
                db.Comments.Add(comment);
                db.SaveChanges();
                //redirects to the movie
                return RedirectToAction("Details", "Movies", new { id = comment.MovieFK });
            }
            return View(comment);
        }

        // GET: Comments/Edit/5
        [Authorize(Roles = "Administrador")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public ActionResult Edit([Bind(Include = "ID,Text")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(comment);
        }

        // GET: Comments/Delete/5
        [Authorize(Roles = "Administrador")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Administrador")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id, String confirm)
        {

            Comment comment = db.Comments.Find(id);
            //value to redirect
            int idValue = comment.MovieFK;

            if (confirm.Equals("Delete"))
            {

                db.Comments.Remove(comment);
                db.SaveChanges();
            }
            return RedirectToAction("Details", "Movies", new { id = idValue });

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SerFy v2.0/Controllers/RatesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SerFy_v2._0.Models;

namespace SerFy_v2._0.Controllers
{
    public class RatesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Rates
        public ActionResult Index()
        {
            return View(db.Rates.ToList());
        }

        // GET: Rates/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rate rate = db.Rates.Find(id);
            if (rate == null)
            {
                return HttpNotFound();
            }
            return View(rate);
        }

        // GET: Rates/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Rates/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MovieFK")]Rate rt, int value)
        {
            //create a rate
            var rate = new Rate();
            
            //create utilizador to get the user
            var utilizador = db.Utilizadores.Where(u => u.email == User.Identity.Name).FirstOrDefault();
            
            //rate userFK will be equals to thee utilizador.ID
            rate.UserFK = utilizador.ID;

            //confirm will get the old rate
            Rate confirm = db.Rates.Where(u => u.MovieFK == rt.MovieFK && u.UserFK == utilizador.ID).FirstOrDefault();

            //if confirm exists
            if (confirm != null)
            {
                //rate selected by the user
                rate.rate = value;
                //confirm id need to fit the rate ID
                rate.ID = confirm.ID;
                // Movie referent to the rate
                rate.MovieFK = rt.MovieFK;
                //delete the rate to create a new one after this
                DeleteConfirmed(confirm.ID);
            }
            else
            {
                //if not rate will be created for the firs time
                //id defenition
                if (db.Rates.Count() == 0)
                {
                    rate.ID = 1;
                }
                else
                {
                    rate.ID = db.Rates.Max(r => r.ID) + 1;
                }
                //value of the rate selected
                rate.rate = value;
                //Movie selected
                rate.MovieFK = rt.MovieFK;
            }
            if (ModelState.IsValid)
            {
                //add the new rate
                db.Rates.Add(rate);
                db.SaveChanges();
                //redirect to the movie view
                return RedirectToAction("Details", "Movies", new { id = rate.MovieFK });

            }

            return View(rate);
        }

        // GET: Rates/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rate rate = db.Rates.Find(id);
            if (rate == null)
            {
                return HttpNotFound();
            }
            return View(rate);
        }
        // POST: Rates/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,rate")] Rate rate)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rate).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(rate);
        }

        // GET: Rates/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rate rate = db.Rates.Find(id);
            if (rate == null)
            {
                return HttpNotFound();
            }
            return View(rate);
        }

        // POST: Rates/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Rate rate = db.Rates.Find(id);
            db.Rates.Remove(rate);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SerFy v2.0/Views/Movies/Create.cshtml
@model SerFy_v2._0.Models.ViewModelCreateFilmePerso

@{
    ViewBag.Title = "Create";
}

<h2>Create a new Movie</h2>


@using (Html.BeginForm("Create", "Movies", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Movie</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photograph, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input class="form-control btn-default" type="file" name="photo" />
                @Html.ValidationMessageFor(model => model.Photograph, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Trailer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Trailer, new { htmlAttributes = new { @class = "form-control", @placeholder = "Only YouTube videos" } })
                @Html.ValidationMessageFor(model => model.Trailer, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.sinopse, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.sinopse, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sinopse, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dataDePub, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                <input min='1800-01-01' required class="form-control btn btn-default" type="date" value="@DateTime.Now.ToString("yyyy-MM-dd")" name="date" />
                @Html.ValidationMessageFor(model => model.dataDePub, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.LabelFor(model => model.idsCharacters)
                @Html.Partial("ListadePersonagens", Model)

            </div>
        </div>

        <div class="form-group">

            <div class="col-md-offset-2 col-md-10">
                @Html.LabelFor(model => model.idsDirectores)
                @Html.Partial("ListDirectors", Model)
            </div>
        </div>

        <div class="form-group">

            <div class="col-md-offset-2 col-md-10">
                @Html.LabelFor(model => model.idsWriters)
                @Html.Partial("ListWriters", Model)
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" value="4" name="valueButton" class="btn btn-default">Create</button>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back", "Index", "", new { @class = "btn btn.default btn-info" })
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SerFy v2.0/Views/Movies/Delete.cshtml
@model SerFy_v2._0.Models.Movie

@{
    ViewBag.Title = "Delete";
}


<div class="center-block center text-center">
    <h3>Are you sure you want to delete @Model.Name ?</h3>

    @using (Html.BeginForm("Delete", "Movies", FormMethod.Post))
    {

        @Html.AntiForgeryToken()
        
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger btn-default" />
            <button class="btn btn-default">
                @Html.ActionLink("I've changed my mind", "Index")
            </button>
        </div>
    }
</div>

SerFy v2.0/Views/Movies/Details.cshtml
@model SerFy_v2._0.Models.Movie

@{
    ViewBag.Title = "Details";
}
@*Coluna para user Admin*@
@if (User.IsInRole("Administrador"))
{
    <div class="container" style="margin-top:40px; margin-bottom:40px;">
        <div class="row">

            <button class="btn btn-default" onclick="location.href='@Url.Action("Edit", "Movies", new { id = Model.ID })'"> Edit Movie @*@Html.ActionLink("Change", "Edit", new { id = Model.ID })*@</button>
            <button class="btn btn-default btn-danger" onclick="location.href='@Url.Action("Delete", "Movies", new { id = Model.ID })'">Delete Movie @*@Html.ActionLink("Delete","Delete",new  { id = Model.ID})*@</button>@*Not working*@
        </div>


    </div>
}
@*fim da coluna user *@


<div class="container" style="margin-top:40px; margin-bottom:40px;">
    @*Referente ao Model Movie*@
    <div class="row">
        <div class="col-lg-4">
            <h2>@Model.Name</h2>
        </div>
        <div class="col-lg-2">
            <h5><b>Release Date:</b>@Model.dataDePub.ToString("dd/MM/yyyy")</h5>
        </div>
        <div class="col-lg-1">
            <h5><b>Rate:</b>@Model.Rating</h5>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-4">
            <img style="object-fit:cover" class="img-rounded" src="~/Multimedia/Filme/@Model.Photograph" width="325" height="500">
        </div>
        <div class="col-lg-8">
            <Iframe height="500" width="800" style="object-fit: fill ; border-radius: 5px; border:solid; overflow: hidden;" src="@Model.Trailer"></Iframe>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <h5><b>Synopse:</b></h5>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <p>@Model.sinopse</p>
        </div>
    </div>

    <hr>
    @*fim*@

    @*Listagem dos atores*@
    <div class="row">
        <div class="col-lg-12">
            <div class="col-lg-4" style="border-left: 1px solid #808080;">
                <table width="350" class="table-striped">
                    <tr>
                        <h4>Actors</h4>
                    </tr>
                    <tr>
                        <th>Name</th>
                        <th>Role</th>
                    </tr>
                    @foreach (var item in Model.CharactersList)
                        {
                        <tr style="cursor:pointer">

                            <td onclick="location.href='@Url.Action("Details", "Actors", new { id = item.actor.ID })'"><img width="20" src="~/Multimedia/Atores/@item.actor.Photograph"> @item.actor.Name</td>

                            <td onclick="location.href=" data-toggle="modal" data-target="#@item.ID"> @item.Name</td>

                            <div class="modal fade" id="@item.ID" role="dialog">
                                <div class="modal-dialog">

                                    <!-- Modal content-->
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                                            <h4 class="modal-title">@item.Name</h4>
                                        </div>
                                        <div style="justify-content:center" class="modal-body">
                                            <img width="500" style="object-fit:cover" class="img-rounded" src="~/Multimedia/Personagens/@item.Photograph" />
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                        </div>
                                    </div>

                                </div>
                            </div>



                        </tr>
                    }
                </table>
            </div>

            @*Listagem dos Diretores*@

            <div style="border-left: 1px solid #808080 " class="col-lg-4">
                <table width="200" class="table-striped">
                    <tr>
                        <h4>Directors</h4>
                    </tr>
                    <tr>
                        <th>Name</th>
                    </tr>
                    @foreach (var item in Model.DirectorList)
                    {
                        <tr style="cursor:pointer">
                            <td onclick="location.href='@Url.Action("Details","Directors",new { id = item.ID })'"><img width="20" src="~/Multimedia/Directores/@item.Photograph"> @item.Name</td>
                        </tr>
                    }
                </table>
            </div>

            @*Listagem dos Escritores*@

            <div class="col-lg-4" style="border-left: 1px solid #808080">
                <table width="200" class="table-striped">

                    <tr>
                        <h4>Writter</h4>
                    </tr>
                    <tr><th> Name</th> </tr>
                    @foreach (var item in Model.WriterList)
                    {
                        <tr style="cursor:pointer">
                            <td onclick="location.href='@Url.Action("Details","Writers",new { id = item.ID })'"><img width="20" src="~/Multimedia/Writers/@item.Photograph"> @item.Name</td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>

    @if (Request.IsAuthenticated)
    {
        <h4>Rates</h4>
        @Html.Partial("_RateForm", new SerFy_v2._0.Models.Rate { MovieFK = Model.ID })
    }

    <h4>Comments</h4>
    
    <hr />
    <div style="margin-left:20px;">
        @foreach (var item in Model.Comments)
        {
            <div class="row">

                <div class="col-lg-2">
                    <table>
                        <tr>
                            <td>
                                <img src="~/Multimedia/Avatares/@item.User.photo" style="width:40px; height:40px; object-fit:cover" class="img-circle" />

                            </td>
                            <td> <p>@Html.DisplayFor(u => item.User.UName)</p></td>
                        </tr>
                    </table>
                </div>
                <div class="col-lg-3">
                    <p>@Html.DisplayFor(u => item.Text)</p>
                    @if (User.IsInRole("Administrador"))
                    {
                        <button class="btn btn-danger" onclick="location.href='@Url.Action("Delete","Comments",new { id = item.ID })'"> Delete </button>
                    }
                </div>
            </div>
            <hr />
        }


        @Html.Partial("_CommentsForm", new SerFy_v2._0.Models.Comment { MovieFK = Model.ID })
    </div>



</div>
<div>
    @Html.ActionLink("Back", "Index", "", new { @class = "btn btn.default btn-info" })
</div>

SerFy v2.0/Views/Movies/Edit.cshtml
@model SerFy_v2._0.Models.viewModelEditFilme

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Movies", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()


    <div class="form-horizontal">
        <h4>Movie</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDvalue)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photograph, htmlAttributes: new { @class = "control-label col-md-2" })
            <button hidden> @Html.EditorFor(model => model.Photograph)</button>
            <div class="col-md-10">
                <p hidden>
                    @Html.EditorFor(model => model.Photograph)
                </p>
                <input class="form-control btn-default" type="file" name="photo" />
                @Html.ValidationMessageFor(model => model.Photograph, "", new { @class = "text-danger" })
            </div>
        </div>
        @*OLD Photos*@
        <div hidden>
            <input value="@Model.Photograph" class="form-control btn-default" type="text" name="oldphoto" />
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.Trailer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Trailer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Trailer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sinopse, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.sinopse, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sinopse, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dataDePub, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <p hidden>
                    @Html.EditorFor(model => model.dataDePub)
                </p>
                <input min='1800-01-01' required type="date" hidden class="form-control btn btn-default" value="@Model.dataDePub.ToString("yyyy-MM-dd")" name="date" />
                @Html.ValidationMessageFor(model => model.dataDePub, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Listcharacters, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <p hidden>
                    @Html.EditorFor(model => model.idsCharacters)
                </p>
                @Html.Partial("ListadePersonagensEdit", Model)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ListDirectors, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <p hidden>
                    @Html.EditorFor(model => model.idsDirectores)
                </p>
                @Html.Partial("ListadeDiretoresEdit", Model)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ListWriters, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <p hidden>
                    @Html.EditorFor(model => model.idsWriters)
                </p>
                @Html.Partial("ListadeEscritoresEdit", Model)
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" value="4" name="valueButton" class="btn btn-default">Save</button>
            </div>
        </div>
    </div>
}


<div>
    @Html.ActionLink("Back", "Details", new { id= Model.IDvalue } , new { @class = "btn btn.default btn-info" })
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SerFy v2.0/Views/Movies/Index.cshtml
@model IEnumerable<SerFy_v2._0.Models.Movie>

@{
    ViewBag.Title = "Index";
}

@if (User.IsInRole("Administrador"))
{
    <button class="btn-default btn" style="margin-top:20px" onclick="location.href='@Url.Action("Create", "Movies")'">Create a new movie</button>
}
<div class="container" style="margin-top: 20px">
    <div class="row" style="text-align: left;margin-left: 10px;">
        <h2 class="text-uppercase">Movies</h2>
    </div>
    <div class="row">
        @foreach (var item in Model)
        {
            <div onmouseover="this.style.opacity='0.7'" onmouseout="this.style.opacity='1'" class="col-lg-3 col-md-3">
                <div class="card" style="margin-top:20px;">

                    <img class="img-rounded" height="300" width="200" style="object-fit: cover; cursor:pointer;" src="~/Multimedia/Filme/@item.Photograph" onclick="location.href='@Url.Action("Details", "Movies", new { id = item.ID })'">

                    <div class="panel-title">
                        <b>@item.Name</b>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

SerFy v2.0/Views/Movies/ListDirectors.cshtml
@model SerFy_v2._0.Models.ViewModelCreateFilmePerso

@{
    ViewBag.Title = "ListDirectors";
}
<div class="container">
    <div class="row">

        @foreach (var Directors in Model.ListDirectors)
        {
            <div class="col-md-4 col-lg-4 col-sm-6 col-xs-6">
                <label>
                    @if (Model.idsCharacters.Contains(Directors.ID))
                    {
                        <input type="checkbox" name="@Html.NameFor(c=>c.idsDirectores)" checked value="@Directors.ID" />

                    }
                    else
                    {
                        <input type="checkbox" name="@Html.NameFor(c=>c.idsDirectores)" value="@Directors.ID" />

                    }
                    @Directors.Name
                </label>
            </div>
        }
    </div>

    <div class="form-group">

        <div class="col-md-offset-2 col-md-10">
            <button class="btn btn-default" name="valueButton" value="2" onclick="location.href='@Url.Action("Create", "Directors")'"> Create a new Director </button>
        </div>
    </div>



</div>

SerFy v2.0/Views/Movies/_CommentsForm.cshtml
@model SerFy_v2._0.Models.Comment

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm("Create", "Comments"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @if (Request.IsAuthenticated)
        {<div class="form-horizontal">
                <h5><b>Create a new Comment: </b></h5>
                @Html.ValidationSummary(true, " ", new { @class = "text-danger" })
                <div>
                    @Html.TextAreaFor(model => model.Text, new { htmlAttributes = new { @placeholder="Write here..." } })
                </div>
                <input type="submit" value="Send Review" class="btn-default btn" />
                @Html.HiddenFor(model => model.MovieFK)
            </div>
        }

    </div>



}
@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}

SerFy v2.0/Views/Movies/_RateForm.cshtml
@model SerFy_v2._0.Models.Rate

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm("Create", "Rates"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @if (Request.IsAuthenticated)
        {<div class="form-horizontal">
                <h5><b>Rate this Movie: </b></h5>
                @Html.ValidationSummary(true, " ", new { @class = "text-danger" })
                <div>
                    <select class="btn btn-default" name="value">
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option selected value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                    </select>

                    <input hidden type="submit" value="Rate" class="btn-default btn" />
                </div>
                @Html.HiddenFor(model => model.MovieFK)
            </div>
        }

    </div>



}
@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}