SerFy v2.0/Models/Characters.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SerFy_v2._0.Models
{
    public class Characters
    {
        [Key]
        public int ID { get; set; }
        [Required]
        public string Name { get; set; }

        public string Photograph { get; set; }

        public virtual ICollection<Movie> MoviesList { get; set; }

        public virtual Actors actor { get; set; }
    }

}

SerFy v2.0/Controllers/ActorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SerFy_v2._0.Models;

namespace SerFy_v2._0.Controllers
{
    public class ActorsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Actors
        public ActionResult Index()
        {
            return View(db.Actors.ToList());
        }

        // GET: Actors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Actors actors = db.Actors.Find(id);
            if (actors == null)
            {
                return HttpNotFound();
            }
            return View(actors);
        }

        [Authorize(Roles = "Administrador")]
        // GET: Actors/Create
        public ActionResult Create()
        {
            //gets the database characters in List format 
            var ch = db.Charas.ToList();
            //creates a new model to alocate the characters
            var model = new ViewModelCreateActors();
            //gets the array length
            model.IdsAllCha = new int[db.Charas.Count()];
            //allocates the Characters List
            model.ListAllCha = ch;
            //retuens the model 
            return View(model);
        }

        // POST: Actors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public ActionResult Create(ViewModelCreateActors Actor, HttpPostedFileBase photo, DateTime Date, int valueButton)
        {
            //adds the list to the param bc this param will be empty
            var p = db.Charas.ToList();
            Actor.ListAllCha = p;

            // verify the button value to redirect
            Actor.ListAllCha = db.Charas;
            if (valueButton == 1)
            {
                return RedirectToAction("Create", "Characters");
            }
            //new actor creation
            Actors newActor = new Actors();
            //define the Actor ID
            int newID;
            if (db.Actors.Count() == 0)
            {
                newID = 1;
            }
            else
            {
                newID = db.Actors.Max(a => a.ID) + 1;
            }
            newActor.ID = newID;

            //List inicialization 
            var chr = db.Charas.ToList();
            Actor.ListCha = chr;

            //Name verification //thas not really necessary tbh
            if (Actor.Name == null)
            {
                ModelState.AddModelError("", "Name not found");
                return View(Actor);

            }

            //define the photo name
            string photoName = "ActorPhoto" + newID;
            //will contain the photo Path
            string pathPhoto = "";

            //if the photo is null then 
            if (photo == null)
            {
                //returns the model state
                ModelState.AddModelError("", "Image not found");
                return View(Actor);
            }
            else
            {
                //if the img format is jpg
                if (photo.ContentType == "image/jpeg")
                {
                    //give the photo a name and a Path
                    photoName = photoName + ".jpg";
                    newActor.Photograph = photoName;
                    pathPhoto = Path.Combine(Server.MapPath("~/Multimedia/Atores/"), photoName);

                }
                else
                {
                    //if not the model state will be returned
                    ModelState.AddModelError("", "Invalid photo type");
                    return View(Actor);

                }

            }
            //Date validation
            if (Date < DateTime.Now)
            {
                newActor.BD = Date;
            }
            else
            {
                ModelState.AddModelError("", "Invalid Date");
                return View(Actor);
            }

            //name attribution
            newActor.Name = Actor.Name;

            //MiniBio attribution 
            newActor.Minibio = Actor.Minibio;

            //CharacerList Validation/attribution
            if (Actor.IdsCha == null)
            {
                ModelState.AddModelError("", "No characters selected");
                return View(Actor);
            }


            //--Add the characters to the List
            //charactersAux was created to add values
            var CharacterAux = new List<Characters> { };
            foreach (var charac in Actor.IdsCha)
            {
                //ch1 is the character object
                Characters ch1 = db.Charas.Find(charac);
                //adds the ch1 to the Characters aux variable
                CharacterAux.Add(ch1);
            }
            //characterList will receive the characterAux Values
            newActor.CharacterList = CharacterAux;


            //ModelState
            if (ModelState.IsValid)
            {
                db.Actors.Add(newActor);
                db.SaveChanges();
                //saves the photo Path
                photo.SaveAs(pathPhoto);
                return RedirectToAction("Index");
            }

            return View(Actor);
        }

        // GET: Actors/Edit/5
        [Authorize(Roles = "Administrador")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //actors will be the object to edit
            Actors actors = db.Actors.Find(id);
            //model is a new model ViewModelEditActors
            var model = new ViewModelEditActors();

            //IdValues allocates the actor ID
            model.IdValue = actors.ID;

            //Name allocates the actor Name
            model.Name = actors.Name;

            //Mini Bio allocates the actor MiniBio
            model.Minibio = actors.Minibio;

            //BD allocates the actor BD(Birth Date)
            model.BD = actors.BD;

            //Photograph allocates the actor Photograph
            model.Photograph = actors.Photograph;

            //IdsAllCha length definition 
            model.IdsAllCha = new int[db.Charas.Count()];

            //ListAllCha will contain every Characcter 
            model.ListAllCha = db.Charas.ToList();

            //------Characters that are already selected
            //var that will go through the Array
            int i = 0;

            //charactersAux is an aux List
            var charactersAux = new List<Characters> { };

            //IdsCha legth definition
            model.IdsCha = new int[actors.CharacterList.Count()];
            //each character will be added into the aux Variable
            foreach (var p in actors.CharacterList)
            {
                model.IdsCha[i] = p.ID;
                charactersAux.Add(p);
                i++;
            }
            // the Characters List will contain the aux values
            model.ListCha = charactersAux;


            if (actors == null)
            {
                return HttpNotFound();
            }
            //return the model
            return View(model);
        }

        // POST: Actors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public ActionResult Edit(ViewModelEditActors actors, HttpPostedFileBase photo, DateTime date, String oldphoto, int valueButton)
        {
            //get the actor
            Actors newActor = db.Actors.Find(actors.IdValue);

            //define List for Model errors
            actors.ListAllCha = db.Charas.ToList();
            actors.ListCha = newActor.CharacterList;

            //button verification
            if (valueButton == 1)
            {
                return RedirectToAction("Create", "Characters");
            }

            //--photo confirmations
            //define the photo name
            string photoName = "ActorPhoto" + newActor.ID;
            //will contain the photo Path
            string pathPhoto = "";

            //if the photo is null then 
            if (photo == null)
            {
                //returns the model state
                actors.Photograph = oldphoto;
            }
            else
            {
                //if the img format is jpg
                if (photo.ContentType == "image/jpeg")
                {
                    //give the photo a name and a Path
                    photoName = "ActorPhoto" + actors.IdValue + ".jpg";
                    pathPhoto = Path.Combine(Server.MapPath("~/Multimedia/Atores/"), photoName);
                    System.IO.File.Delete(pathPhoto);
                    actors.Photograph = photoName;
                    photo.SaveAs(pathPhoto);

                }
                else
                {
                    //if not the model state will be returned
                    actors.BD = newActor.BD;
                    ModelState.AddModelError("", "Invalid photo type");
                    return View(actors);

                }

            }

            //date confirmations
            if (date > DateTime.Now)
            {
                //if date is above todays date then the error will appear
                actors.BD = newActor.BD;
                ModelState.AddModelError("", "Invalid date");

SerFy v2.0/Controllers/CharactersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SerFy_v2._0.Models;

namespace SerFy_v2._0.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class CharactersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Characters
        public ActionResult Index()
        {
            return RedirectToAction("Index", "Movies");
        }

        // GET: Characters/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Characters characters = db.Charas.Find(id);
            if (characters == null)
            {
                return HttpNotFound();
            }
            return View(characters);
        }

        // GET: Characters/Create
        [Authorize(Roles = "Administrador")]
        public ActionResult Create()
        {

            return View();
        }

        // POST: Characters/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name")] Characters characters, HttpPostedFileBase photo)
        {

            //define the Character ID   
            int newID;
            if (db.Charas.Count() == 0)
            {
                newID = 1;

            }
            else
            {
                newID = db.Charas.Max(a => a.ID) + 1;
            }
            characters.ID = newID;
            ////validates the name
            //if (characters.Name == null) {
            //    ModelState.AddModelError("", "No name found");
            //    return View(characters);
            //}

            //define the photo path and validate it
            string photoName = "CharaPhoto" + newID;
            string pathPhoto = "";


            if (photo == null)
            {
                ModelState.AddModelError("", "Image not found");
                return View(characters);
            }
            else
            {
                if (photo.ContentType == "image/jpeg")
                {
                    photoName = photoName + ".jpg";
                    characters.Photograph = photoName;
                    pathPhoto = Path.Combine(Server.MapPath("~/Multimedia/Personagens/"), photoName);

                }
                else
                {

                    ModelState.AddModelError("", "Invalid photo");

                }

            }




            if (ModelState.IsValid)
            {
                db.Charas.Add(characters);
                db.SaveChanges();
               photo.SaveAs(pathPhoto);
                return RedirectToAction("Index", "Movies");
            }

            return View(characters);
        }

        // GET: Characters/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Characters characters = db.Charas.Find(id);
            if (characters == null)
            {
                return HttpNotFound();
            }
            return View(characters);
        }

        // POST: Characters/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Photograph")] Characters characters)
        {
            if (ModelState.IsValid)
            {
                db.Entry(characters).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(characters);
        }

        // GET: Characters/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Characters characters = db.Charas.Find(id);
            if (characters == null)
            {
                return HttpNotFound();
            }
            return View(characters);
        }

        // POST: Characters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Characters characters = db.Charas.Find(id);

            characters.MoviesList = new List<Movie> { };
            foreach (var ch in characters.MoviesList.ToList())
            {
                characters.MoviesList.Remove(ch);
            }

            characters.actor = new Actors();

            characters.actor = null;
            db.Charas.Remove(characters);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SerFy v2.0/Views/Characters/Create.cshtml
@model SerFy_v2._0.Models.Characters

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Characters", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Characters</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photograph, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input class="form-control btn btn-default btn btn-default" type="file" name="photo" />
                @Html.ValidationMessageFor(model => model.Photograph, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SerFy v2.0/Views/Characters/Delete.cshtml
@model SerFy_v2._0.Models.Characters

@{
    ViewBag.Title = "Delete";
}


@{
    ViewBag.Title = "Delete";
}

<div class="center-block center text-center">
    <h3>Are you sure you want to delete @Model.Name information ?</h3>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger btn-default" />
            <button class="btn btn-default">
                @Html.ActionLink("I've changed my mind", "Actors", "Index")
            </button>
        </div>
    }
</div>

SerFy v2.0/Views/Characters/Details.cshtml
@model SerFy_v2._0.Models.Characters

@{
    ViewBag.Title = "Details";
}

<div>
    <h2>@Model.Name</h2>
    
    <img width="100" src="~/Multimedia/Personagens/@Model.Photograph"/>


</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SerFy v2.0/Views/Characters/Edit.cshtml
@model SerFy_v2._0.Models.Characters

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Characters</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photograph, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Photograph, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Photograph, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SerFy v2.0/Views/Characters/Index.cshtml
@model IEnumerable<SerFy_v2._0.Models.Characters>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Photograph)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Photograph)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>