SerFy v2.0/Models/Director.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SerFy_v2._0.Models
{
    public class Director
    {
        [Key]
        //Id value
        public int ID { get; set; }
        
        //Director Name
        public string Name { get; set; }
        
        //Director Photograph
        public string Photograph { get; set; }
        
        //Director Birth Date
        [Display(Name="Birth Date")]
        public DateTime Place_BD { set; get; }
        
        //Director Biography
        [Display(Name="Biography")]
        public string MiniBio { get; set; }
        
        //Director Movies
        [Display(Name="Movies")]
        public virtual ICollection<Movie> MovieList { get; set; }
    }
}

SerFy v2.0/Controllers/DirectorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SerFy_v2._0.Models;

namespace SerFy_v2._0.Controllers
{
    public class DirectorsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Directors
        public ActionResult Index()
        {
            return View(db.Directores.ToList());
        }

        // GET: Directors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Director director = db.Directores.Find(id);
            if (director == null)
            {
                return HttpNotFound();
            }
            return View(director);
        }

        // GET: Directors/Create
        [Authorize(Roles = "Administrador")]
        public ActionResult Create()
        {

            var newDirector = new ViewModelCreateDirector();
            newDirector.MovieAllFK = new int[db.Movies.Count()];
            newDirector.MovieAllList = db.Movies.ToList();

            return View(newDirector);
        }

        // POST: Directors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Administrador")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ViewModelCreateDirector director, HttpPostedFileBase photo, DateTime date, int valueButton)
        {
            //create a new Director
            var newDir = new Director();
            
            //give the director the ingo for modelStates
            director.MovieAllFK =new int[db.Movies.Count()];
            director.MovieAllList = db.Movies.ToList();
            
            //button to redirect 
            if (valueButton == 1)
            {
                return RedirectToAction("Create", "Movies");
            }
            
            //define the Director ID
            int newID;
            if (db.Directores.Count() == 0)
            {
                newID = 1;
            }
            else
            {
                newID = db.Directores.Max(a => a.ID) + 1;
            }
            newDir.ID = newID;

           

            //Name verification //not necessary 
            if (director.Name == null)
            {
                ModelState.AddModelError("", "Name not found");
                return View(director);

            }

            //define the photo Name
            string photoName = "DirectorPhoto" + newID;
            //will have the photo path
            string pathPhoto = "";


            if (photo == null)
            {
                //if fot is null then
                ModelState.AddModelError("", "Image not found");
                return View(director);
            }
            else
            {
                if (photo.ContentType == "image/jpeg")
                {
                    //if photo is jpg than save it and « add it to the model 
                    photoName = photoName + ".jpg";
                    newDir.Photograph = photoName;
                    pathPhoto = Path.Combine(Server.MapPath("~/Multimedia/Directores/"), photoName);

                }
                else
                {
                    //if the photo is invalid
                    ModelState.AddModelError("", "Invalid photo type");
                    return View(director);

                }

            }
            //Date validation
            if (date < DateTime.Now)
            {
                newDir.Place_BD = date;
            }
            else
            {
                ModelState.AddModelError("", "Invalid Date");
                return View(director);
            }

            //name attribution
            newDir.Name = director.Name; 

            //bio attribution
            newDir.MiniBio = director.MiniBio;

            //Movies List  Validation/attribution
            if (director.MovieFK == null)
            {
                //director can be created without a Movie
                director.MovieFK = new int[0];
            }

            //----add movies
            //add an empty List to the model
            newDir.MovieList = new List<Movie> { };

            //each movie selected goes into the Movie Lisst
            foreach (var mov in director.MovieFK.ToList())
            {
                Movie movie = db.Movies.Find(mov);

                newDir.MovieList.Add(movie);
            }

            if (ModelState.IsValid)
            {
                db.Directores.Add(newDir);
                db.SaveChanges();
                //saves the photo
                photo.SaveAs(pathPhoto);
                return RedirectToAction("Index");
            }

            return View(director);
        }

        [Authorize(Roles = "Administrador")]
        // GET: Directors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //finds the director
            Director director = db.Directores.Find(id);
             if (director == null)
            {
                return HttpNotFound();
            }
             //creates a new Model
            var newDir = new ViewModelEditDirector();
            //values definition----
            newDir.IDValue = director.ID;
            newDir.MiniBio = director.MiniBio;
            newDir.Name = director.Name;
            newDir.Photograph = director.Photograph;
            newDir.Place_BD = director.Place_BD;
            //MovieFk will be the array with all the Movies ids 
            newDir.MovieAllFK = new int[db.Movies.Count()];
            //MovirAllList List will have the database
            newDir.MovieAllList = db.Movies.ToList();

            //i will be an auxiliar int
            int i = 0;
            //dirAux is an auviliar List<Movie>
            var dirAux = new List<Movie> { };
            //MovieFK
            newDir.MovieFK = new int[director.MovieList.Count()];
            //each director will have the selected movies
            foreach (var p in director.MovieList)
            {
                newDir.MovieFK[i] = p.ID;
                dirAux.Add(p);
                i++;
            }
            //Movie Lis is equals to the auxiliar var
            newDir.MovieList = dirAux;
            
            //retuins the model
            return View(newDir);
        }

        // POST: Directors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Administrador")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ViewModelEditDirector director, String oldphoto, HttpPostedFileBase photo, DateTime date, int valueButton)
        {
            //get the director
            Director dir = db.Directores.Find(director.IDValue);
            director.MovieAllList = db.Movies.ToList();
            director.MovieList = dir.MovieList;


            
            //button verification
            if (valueButton == 1)
            {
                return RedirectToAction("Create", "Movies");
            }
            //--photo confirmations
            //photo name variable
            string photoName = "DirectorPhoto" + dir.ID;
            //photo path variable
            string pathPhoto = "";
            //photo validations and names
            
            /*This will verify the photo this one needs to be jpg and not null*/
            if (photo == null)
            {
                
                director.Photograph = oldphoto;

            }
            else
            {
                if (photo.ContentType == "image/jpeg")
                {
                    photoName = "ActorPhoto" + director.IDValue + ".jpg";
                    pathPhoto = Path.Combine(Server.MapPath("~/Multimedia/Directores/"), photoName);
                    System.IO.File.Delete(pathPhoto);
                    director.Photograph = photoName;
                    photo.SaveAs(pathPhoto);

                }
                else
                {
                    director.Place_BD = dir.Place_BD;
                    ModelState.AddModelError("", "Invalid photo type");
                    return View(director);
                }

            }
            

            //date confirmations
            if (date > DateTime.Now)
            {
                //if date is invalid
                director.Place_BD = dir.Place_BD;
                ModelState.AddModelError("", "Invalid date");
                return View(director);
            }
            else
            {
                //if date is valid
                director.Place_BD = date;
            }

            //List confirmation
            if (director.MovieFK == null)
            {
                int i = 0;
                director.MovieFK = new int[dir.MovieList.Count()];
                foreach (var mov in dir.MovieList) {
                    director.MovieFK[i] = mov.ID;
                    i++;
                }
                ModelState.AddModelError("","No Movie Selected");
                return View(director);

            }

            //get and define the Movies
            //------------------Put the ModelState
            foreach (var allmov in director.MovieAllFK)
            {
                Movie m = db.Movies.Find(allmov);
                if (dir.MovieList.Contains(m))
                {
                    dir.MovieList.Remove(m);
                }
            }

SerFy v2.0/Views/Directors/Create.cshtml
@model SerFy_v2._0.Models.ViewModelCreateDirector

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>



@using (Html.BeginForm("Create", "Directors", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Director</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photograph, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input class="form-control btn-default" type="file" name="photo" />
                @Html.ValidationMessageFor(model => model.Photograph, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Place_BD, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input min='1800-01-01' required class="form-control btn btn-default" type="date" value="@DateTime.Now.ToString("yyyy-MM-dd")" name="date" />
                @Html.ValidationMessageFor(model => model.Place_BD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MiniBio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.MiniBio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MiniBio, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">

            <div class="col-md-offset-2 col-md-10">
                @Html.LabelFor(model => model.MovieFK)
                @Html.Partial("ListDirCreate", Model)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" value="2" name="valueButton" class="btn btn-default">Create</button>
            </div>
        </div>
    </div>
}


<div>
    @Html.ActionLink("Directors", "Index", "", new { @class = "btn btn-default btn-info" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SerFy v2.0/Views/Directors/Delete.cshtml
@model SerFy_v2._0.Models.Director

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Director</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photograph)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photograph)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Place_BD)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Place_BD)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MiniBio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MiniBio)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SerFy v2.0/Views/Directors/Details.cshtml
@model SerFy_v2._0.Models.Director

@{
    ViewBag.Title = "Details";
}

@if (User.IsInRole("Administrador"))
{
    <div class="container" style="margin-top:30px">
        <div class="row">
            <button class="btn btn-default" onclick="location.href='@Url.Action("Edit", "Directors", new { id = Model.ID })'">@*@Html.ActionLink("Change", "Edit", new { id = Model.ID })*@Edit Director</button>
            <button class="btn btn-default btn-danger" onclick="location.href='@Url.Action("Delete", "Directors", new { id = Model.ID })'">@*@Html.ActionLink("Delete", "Delete", new { id = Model.ID })*@Delete Director</button>
        </div>
    </div>
}
<div class="container" style="margin-bottom:40px;margin-top:40px">
    <div class="row">
        <div class="col-lg-4">
            <img class="img-rounded" style="object-fit:cover" height="500" width="350" src="~/Multimedia/Directores/@Model.Photograph" />
        </div>
        <div class="col-lg-4">
            <p style="margin-top:5px"><b>Name :</b>@Model.Name</p>
            <p style="margin-top:5px"><b>Biography :</b>@Model.MiniBio</p>
            <p style="margin-top:5px"><b>Birthday:</b> @Model.Place_BD.ToString("dd/MM/yyyy")</p>
            <p style="margin-top:5px"><b>Movie:</b></p>
            <div class="container"></div>
            <div class="row">
                @foreach (var i in Model.MovieList)
                {
                    <div class="col-lg-4" style="position: relative; text-align: center; color: black;" onclick="location.href='@Url.Action("Details", "Movies", new { id = i.ID })'">
                        <img src="~/Multimedia/Filme/@i.Photograph" style="cursor:pointer" class="img-rounded img-responsive" />
                        @i.Name
                    </div>
                }

            </div>
        </div>
    </div>
</div>

<div>
    @Html.ActionLink("Back", "Index","", new { @class = "btn btn-default btn-info" })
</div>

SerFy v2.0/Views/Directors/Edit.cshtml
@model SerFy_v2._0.Models.ViewModelEditDirector

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Directors", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Director</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDValue)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Photograph, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input class="form-control btn-default" type="file" name="photo" />
                <label hidden>
                    <input value="@Model.Photograph" class="form-control btn-default" type="text" name="oldphoto" />
                </label>
                @Html.ValidationMessageFor(model => model.Photograph, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Place_BD, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input min='1800-01-01' required class="form-control btn btn-default" type="date" value="@Model.Place_BD.ToString("yyyy-MM-dd")" name="date" />
                @Html.ValidationMessageFor(model => model.Place_BD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MiniBio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.MiniBio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MiniBio, "", new { @class = "text-danger" })
            </div>
        </div>
        @*Partial View*@
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.LabelFor(model => model.MovieFK)
                @Html.Partial("ListDirEdit", Model)
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" value="2" name="valueButton" class="btn btn-default">Save</button>
            </div>
        </div>

    </div>

}
<div>
    @Html.ActionLink("Back", "Details", new { id = Model.IDValue }, new { @class = "btn btn-default btn-info" })
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SerFy v2.0/Views/Directors/Index.cshtml
@model IEnumerable<SerFy_v2._0.Models.Director>

@{
    ViewBag.Title = "Index";
}

@if (User.IsInRole("Administrador"))
{
    <button class="btn-default btn" onclick="location.href='@Url.Action("Create", "Directors")'" style="margin-top:20px"> Create a new Director </button>
}
    <div class="container" style="margin-top: 20px;">
        <div class="row" style="text-align: left;margin-left: 10px;">
            <h2 class="text-uppercase">Directors</h2>
        </div>
        <div class="row">
            @foreach (var item in Model)
            {
                <div onmouseover="this.style.opacity='0.7'" onmouseout="this.style.opacity='1'" class="col-lg-3 col-md-3">
                    <div class="card" style="margin-top:20px;">
                        <img height="300" width="200" class="img-rounded" style="cursor:pointer; object-fit:cover;" src="~/Multimedia/Directores/@item.Photograph" onclick="location.href='@Url.Action("Details", "Directors", new { id = item.ID })'">
                        <div class="container">
                            <h4><b>@item.Name</b></h4>
                            @*<button class="btn btn-default">@Html.ActionLink("Edit Director", "Edit", new { id = item.ID })</button>*@
                        </div>
                    </div>
                </div>


            }
        </div>
    </div>

SerFy v2.0/Views/Directors/ListDirCreate.cshtml
@model SerFy_v2._0.Models.ViewModelCreateDirector

@{
    ViewBag.Title = "ListDirCreate";
}

<div class="container">
    <div class="row">
        @foreach (var mov in Model.MovieAllList)
        {
            <div class="col-md-4 col-lg-4 col-sm-6 col-xs-6">
                <label>
                  
                        <input type="checkbox"  name="@Html.NameFor(c => c.MovieFK)" value="@mov.ID" />
                        @mov.Name

                   
                </label>
                <label hidden>
                    <input name="@Html.NameFor(c => c.MovieAllFK)" value="@mov.ID" />
                </label>

            </div>

        }


        @*<label hidden>
                <input type="checkbox" name="@Html.NameFor(c => c.IdsAllCha)" value="@charac.ID" />
            </label>
            @if (charac.actor == null)
            {

                <label>
                    <input type="checkbox" name="@Html.NameFor(c => c.IdsCha)" value="@charac.ID" />
                    @charac.Name
                </label>*@



        <div class="form-group">

            <div class="col-md-offset-2 col-md-10">
                <button class="btn btn-default" name="valueButton" value="1" onclick="location.href='@Url.Action("Create", "Movies")'"> Create a new Movie </button>

            </div>
        </div>

    </div>
</div>

SerFy v2.0/Views/Directors/ListDirEdit.cshtml
@model SerFy_v2._0.Models.ViewModelEditDirector

@{
    ViewBag.Title = "ListDirEdit";
}

<div class="container">
    <div class="row">
        @foreach (var mov in Model.MovieAllList)
        {
            <div class="col-md-4 col-lg-4 col-sm-6 col-xs-6">
                <label>
                    @if (Model.MovieFK.Contains(mov.ID))
                    {
                        <input type="checkbox" checked name="@Html.NameFor(c => c.MovieFK)" value="@mov.ID" />
                        @mov.Name
                    }
                    else
                    {
                        <input type="checkbox"  name="@Html.NameFor(c => c.MovieFK)" value="@mov.ID" />
                        @mov.Name

                    }
                </label>
                <label hidden>
                    <input name="@Html.NameFor(c => c.MovieAllFK)" value="@mov.ID" />
                </label>

            </div>

        }


        @*<label hidden>
                <input type="checkbox" name="@Html.NameFor(c => c.IdsAllCha)" value="@charac.ID" />
            </label>
            @if (charac.actor == null)
            {

                <label>
                    <input type="checkbox" name="@Html.NameFor(c => c.IdsCha)" value="@charac.ID" />
                    @charac.Name
                </label>*@



        <div class="form-group">

            <div class="col-md-offset-2 col-md-10">
                <button class="btn btn-default" name="valueButton" value="1" onclick="location.href='@Url.Action("Create", "Movies")'"> Create a new Movie </button>

            </div>
        </div>

    </div>
</div>