SerFy v2.0/Models/Writer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SerFy_v2._0.Models
{
    public class Writer
    {
        [Key]
        //Id value
        public int ID { get; set; }
        //Name
        [Required(ErrorMessage ="Name is required")]
        public string Name { get; set; }
        //Photograph
        public string Photograph { get; set; }
        //Writer Birth Date
        public DateTime Place_DB { get; set; }
        //Biography
        [Required(ErrorMessage = "Biography is required")]
        [Display(Name= "Biography")]
        public string MiniBio { get; set; }
        //Movies List
        [Display(Name="Movies")]
        public virtual ICollection<Movie> MoviesList { get; set; }
    }
}

SerFy v2.0/Controllers/WritersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SerFy_v2._0.Models;

namespace SerFy_v2._0.Controllers
{
    public class WritersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Writers
        public ActionResult Index()
        {
            return View(db.Writers.ToList());
        }

        // GET: Writers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Writer writer = db.Writers.Find(id);
            if (writer == null)
            {
                return HttpNotFound();
            }
            return View(writer);
        }

        // GET: Writers/Create
        [Authorize(Roles = "Administrador")]
        public ActionResult Create()
        {
            //create a new Model
            var newWriter = new ViewModelCreateWriter();
            //get the Fks ids
            newWriter.MovieAllFK = new int[db.Movies.Count()];
            //get the objects
            newWriter.MovieAllList = db.Movies.ToList();

            return View(newWriter);
        }

        // POST: Writers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Administrador")]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ViewModelCreateWriter writer, HttpPostedFileBase photo, DateTime date, int valueButton)
        {
            var newWriter = new Writer();

            writer.MovieAllFK = new int[db.Movies.Count()];
            writer.MovieAllList = db.Movies.ToList();

            if (valueButton == 1)
            {
                return RedirectToAction("Create", "Movies");
            }

            //define the writer ID
            int newID;
            if (db.Writers.Count() == 0)
            {
                newID = 1;
            }
            else
            {
                newID = db.Writers.Max(a => a.ID) + 1;
            }
            newWriter.ID = newID;



            //Name verification
            if (writer.Name == null)
            {
                ModelState.AddModelError("", "Name not found");
                return View(writer);

            }

            //define the photo path
            string photoName = "WriterPhoto" + newID;
            string pathPhoto = "";


            if (photo == null)
            {
                ModelState.AddModelError("", "Image not found");
                return View(writer);
            }
            else
            {
                if (photo.ContentType == "image/jpeg")
                {
                    photoName = photoName + ".jpg";
                    newWriter.Photograph = photoName;
                    pathPhoto = Path.Combine(Server.MapPath("~/Multimedia/Writers/"), photoName);

                }
                else
                {

                    ModelState.AddModelError("", "Invalid photo");
                    return View(writer);

                }

            }
            //Date validation
            if (date < DateTime.Now)
            {
                newWriter.Place_DB = date;
            }
            else
            {
                ModelState.AddModelError("", "Invalid Date");
                return View(writer);
            }
            //name and bio attribution
            newWriter.Name = writer.Name;
            newWriter.MiniBio = writer.MiniBio;
            //Movies List  Validation/attribution
            if (writer.MovieFK == null)
            {
               //writer can be created without a Movie
                writer.MovieFK = new int[0];
            }
            //add a movie
            newWriter.MoviesList = new List<Movie> { };
            //each movie selected will be added into the MovieList
            foreach (var mov in writer.MovieFK.ToList())
            {
                Movie movie = db.Movies.Find(mov);

                newWriter.MoviesList.Add(movie);
            }


            if (ModelState.IsValid)
            {
                db.Writers.Add(newWriter);
                db.SaveChanges();
                //saves the photo
                photo.SaveAs(pathPhoto);
                return RedirectToAction("Index");
            }

            return View(writer);
        }

        // GET: Writers/Edit/5
        [Authorize(Roles = "Administrador")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Writer writer = db.Writers.Find(id);
            if (writer == null)
            {
                return HttpNotFound();
            }
            //create a new Model
            var newWr = new ViewModelEditWriter();
            //give the writer calues to the model
            newWr.IDValue = writer.ID;
            newWr.MiniBio = writer.MiniBio;
            newWr.Name = writer.Name;
            newWr.Photograph = writer.Photograph;
            newWr.Place_BD = writer.Place_DB;
            //give the length and all the Moves database  List
            newWr.MovieAllFK = new int[db.Movies.Count()];
            newWr.MovieAllList = db.Movies.ToList();

            //get the defined List values
            int i = 0;
            var WRAux = new List<Movie> { };
            newWr.MovieFK = new int[writer.MoviesList.Count()];
            foreach (var p in writer.MoviesList)
            {
                newWr.MovieFK[i] = p.ID;
                WRAux.Add(p);
                i++;
            }
            newWr.MovieList = WRAux;

            return View(newWr);
        }

        // POST: Writers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Administrador")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ViewModelEditWriter writer, String oldphoto, HttpPostedFileBase photo, DateTime date, int valueButton)
        {

            //get the Writer
            Writer wr = db.Writers.Find(writer.IDValue);
            // give the writer values to the model ro Modelstates
            writer.MovieAllList = db.Movies.ToList();
            writer.MovieList = wr.MoviesList;
            //button verification
            if (valueButton == 1)
            {
                return RedirectToAction("Create", "Movies");
            }
            //--photo confirmations
            //photo name variable
            string photoName = "WriterPhoto" + wr.ID;
            //photo path variable
            string pathPhoto = "";
          

            //photo validations and names
            if (photo == null)
            {
                writer.Photograph = wr.Photograph;
            }
            else
            {
                if (photo.ContentType == "image/jpeg")
                {
                    photoName = photoName + ".jpg";
                    wr.Photograph = photoName;
                    pathPhoto = Path.Combine(Server.MapPath("~/Multimedia/Writers/"), photoName);

                }
                else
                {
                    writer.Place_BD= wr.Place_DB;
                    ModelState.AddModelError("", "Invalid photo");
                    return View(writer);

                }

            }

            //date confirmations
            if (date > DateTime.Now)
            {
                writer.Place_BD = wr.Place_DB;
                ModelState.AddModelError("", "Invalid date");
                return View(writer);
            }
            else
            {
                writer.Place_BD = date;
            }
            //List confirmation
            if (writer.MovieFK == null)
            {
                int i = 0;
                writer.MovieFK = new int[wr.MoviesList.Count()];
                foreach (var mov in wr.MoviesList)
                {
                    writer.MovieFK[i] = mov.ID;
                    i++;
                }
                ModelState.AddModelError("", "No Movie Selected");
                return View(writer);
            }
                //get and define the Movies
                //------------------Put the ModelState
                foreach (var allmov in writer.MovieAllFK)
            {
                Movie m = db.Movies.Find(allmov);
                if (wr.MoviesList.Contains(m))
                {
                    wr.MoviesList.Remove(m);
                }
            }
            //add data
            foreach (var mov in writer.MovieFK.ToList())
            {
                Movie movie = db.Movies.Find(mov);
                if (!wr.MoviesList.Contains(movie))
                {
                    wr.MoviesList.Add(movie);
                }
            }
            //Director entries
            wr.Name = writer.Name;
            wr.MiniBio = writer.MiniBio;
            wr.ID = writer.IDValue;
            wr.Photograph = writer.Photograph;
            wr.Place_DB = writer.Place_BD;

            if (ModelState.IsValid)
            {
                db.Entry(wr).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(writer);
        }

        // GET: Writers/Delete/5
         [Authorize(Roles = "Administrador")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

SerFy v2.0/Views/Writers/Create.cshtml
@model SerFy_v2._0.Models.ViewModelCreateWriter

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Writers", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Writer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photograph, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input class="form-control btn-default" type="file" name="photo" />

                @Html.ValidationMessageFor(model => model.Photograph, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Place_DB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input min='1800-01-01' required class="form-control btn btn-default" type="date" value="@DateTime.Now.ToString("yyyy-MM-dd")" name="date" />

                @Html.ValidationMessageFor(model => model.Place_DB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MiniBio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.MiniBio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MiniBio, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">

            <div class="col-md-offset-2 col-md-10">
                @Html.LabelFor(model => model.MoviesList)
                @Html.Partial("ListActCreate", Model)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" value="2" name="valueButton" class="btn btn-default">Create</button>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Writers", "Index","",new { @class="btn btn.default btn-info"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SerFy v2.0/Views/Writers/Delete.cshtml
@model SerFy_v2._0.Models.Writer

@{
    ViewBag.Title = "Delete";
}

<div class="center-block center text-center">
    <h3>Are you sure you want to delete @Model.Name information ?</h3>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger btn-default" />
            <button class="btn btn-default">
                @Html.ActionLink("I've changed my mind", "Index")
            </button>
        </div>
    }
</div>

SerFy v2.0/Views/Writers/Details.cshtml
@model SerFy_v2._0.Models.Writer

@{
    ViewBag.Title = "Details";
}

@if (User.IsInRole("Administrador"))
{
    <div class="container" style="margin-top:30px">
        <div class="row">
            <button class="btn btn-default" onclick="location.href='@Url.Action("Edit", "Writers", new { id = Model.ID })'">@*@Html.ActionLink("Change", "Edit", new { id = Model.ID })*@Edit Writer</button>
            <button class="btn btn-default btn-danger" onclick="location.href='@Url.Action("Delete", "Writers", new { id = Model.ID })'">@*@Html.ActionLink("Delete", "Delete", new { id = Model.ID })*@Delete Writer</button>
        </div>
    </div>
}

<div class="container" style="margin-bottom:40px;margin-top:40px">
    <div class="row">
        <div class="col-lg-4">
            <img class="img-rounded" style="object-fit:cover" height="500" width="350" src="~/Multimedia/Writers/@Model.Photograph" />
        </div>
        <div class="col-lg-4">
            <p style="margin-top:5px"><b>Name :</b>@Model.Name</p>
            <p style="margin-top:5px"><b>Biography :</b>@Model.MiniBio</p>
            <p style="margin-top:5px"><b>Birthday:</b> @Model.Place_DB.ToString("dd/MM/yyyy")</p>
            <p style="margin-top:5px"><b>Movies written:</b></p>
            <div class="container"></div>
            <div class="row">
                @foreach (var i in Model.MoviesList)
                {
                    <div class="col-lg-4" style="position: relative; text-align: center; color: black;" onclick="location.href='@Url.Action("Details", "Movies", new { id = i.ID })'">
                        <img src="~/Multimedia/Filme/@i.Photograph" style="cursor:pointer" class="img-rounded img-responsive" />
                        @i.Name
                    </div>
                }

            </div>
        </div>
    </div>
</div>

<div>
    @Html.ActionLink("Back", "Index", "", new { @class = "btn btn.default btn-info" })
</div>

SerFy v2.0/Views/Writers/Edit.cshtml
@model SerFy_v2._0.Models.ViewModelEditWriter

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>



@using (Html.BeginForm("Edit", "Writers", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Writer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDValue)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photograph, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input class="form-control btn-default" type="file" name="photo" />
                <label hidden>
                    <input value="@Model.Photograph" class="form-control btn-default" type="text" name="oldphoto" />
                </label>
                @Html.ValidationMessageFor(model => model.Photograph, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Place_BD, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input min='1800-01-01' required class="form-control btn btn-default" type="date" value="@DateTime.Now.ToString("yyyy-MM-dd")" name="date" />

                @Html.ValidationMessageFor(model => model.Place_BD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MiniBio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.MiniBio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MiniBio, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">

            <div class="col-md-offset-2 col-md-10">
                @Html.LabelFor(model => model.MovieList)
                @Html.Partial("ListActEdit", Model)
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" value="2" name="valueButton" class="btn btn-default">Save</button>
            </div>
        </div>

    </div>
}

<div>
    @Html.ActionLink("Back", "Details", new { id = Model.IDValue }, new { @class = "btn btn.default btn-info" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SerFy v2.0/Views/Writers/Index.cshtml
@model IEnumerable<SerFy_v2._0.Models.Writer>

@{
    ViewBag.Title = "Index";
}

@if (User.IsInRole("Administrador"))
{
    <button class="btn-default btn" onclick="location.href='@Url.Action("Create", "Writers")'" style="margin-top:20px"> Create a new Writer </button>
}

<div class="container" style="margin-top:20px">
    <div class="row" style="text-align: left;margin-left: 10px;">
        <h2 class="text-uppercase">Writers</h2>
    </div>
    <div class="row">
        @foreach (var item in Model)
        {
            <div onmouseover="this.style.opacity='0.7'" onmouseout="this.style.opacity='1'" class="col-lg-3 col-md-3">
                <div class="card" style="margin-top:20px;">
                    <img style="object-fit:cover; cursor:pointer;" class=" img-rounded" height="300" width="200" src="~/Multimedia/Writers/@item.Photograph" onclick="location.href='@Url.Action("Details", "Writers", new { id = item.ID })'">
                    <div class="container">
                        <h4><b>@item.Name</b></h4>
                    </div>
                </div>
            </div>


        }
    </div>
</div>

SerFy v2.0/Views/Writers/ListActCreate.cshtml
@model SerFy_v2._0.Models.ViewModelCreateWriter

@{
    ViewBag.Title = "ListDirCreate";
}

<div class="container">
    <div class="row">
        @foreach (var mov in Model.MovieAllList)
        {
            <div class="col-md-4 col-lg-4 col-sm-6 col-xs-6">
                <label>

                    <input type="checkbox" name="@Html.NameFor(c => c.MovieFK)" value="@mov.ID" />
                    @mov.Name


                </label>
                <label hidden>
                    <input name="@Html.NameFor(c => c.MovieAllFK)" value="@mov.ID" />
                </label>

            </div>

        }


        <div class="form-group">

            <div class="col-md-offset-2 col-md-10">
                <button class="btn btn-default" name="valueButton" value="1" onclick="location.href='@Url.Action("Create", "Movies")'"> Create a new Movie </button>

            </div>
        </div>

    </div>
</div>

SerFy v2.0/Views/Writers/ListActEdit.cshtml
@model SerFy_v2._0.Models.ViewModelEditWriter

@{
    ViewBag.Title = "ListActCreate";
}

<div class="container">
    <div class="row">
        @foreach (var mov in Model.MovieAllList)
        {
            <div class="col-md-4 col-lg-4 col-sm-6 col-xs-6">
                <label>
                    @if (Model.MovieFK.Contains(mov.ID))
                    {
                        <input type="checkbox" checked name="@Html.NameFor(c => c.MovieFK)" value="@mov.ID" />
                        @mov.Name
                    }
                    else
                    {
                        <input type="checkbox" name="@Html.NameFor(c => c.MovieFK)" value="@mov.ID" />
                        @mov.Name

                    }
                </label>
                <label hidden>
                    <input name="@Html.NameFor(c => c.MovieAllFK)" value="@mov.ID" />
                </label>

            </div>

        }

        <div class="form-group">

            <div class="col-md-offset-2 col-md-10">
                <button class="btn btn-default" name="valueButton" value="1" onclick="location.href='@Url.Action("Create", "Movies")'"> Create a new Movie </button>

            </div>
        </div>

    </div>
</div>